- polybar-scripts/player-cmus/README.md
It feels like some random markdown was accidentally inserted in the script. Or was it some kind of placeholder and there is something I didn't understand?
Either way everything worked once I removed that bit...
> Update cmus script

- polybar-scripts/openweathermap-fullfeatured/openweathermap-fullfeatured.sh
The date command has different options on FreeBSD systems.
> Fix get_duration() on FreeBSD

- polybar-scripts/info-redshift-temp/info-redshift-temp.sh
This script previously fetched ':' and tried to compare it to an integer. Changed it so that it fetches for example '5000K' and then cuts 'K' instead of the ':' from '..temperature: 5000K'.
Changed the command from
$ redshift -p 2> /dev/null | grep temp | cut -d " " -f 2 | tr -d "[:alpha:]"
to
$ redshift -p 2> /dev/null | grep temp | cut -d " " -f 3 | tr -d "[:alpha:]"
Explanation:
$ redshift -p 2> /dev/null | grep temp
yields
Color temperature: 5000K
piped into 'cut -d " " -f 2' gives
:
while piped into 'cut -d " " -f 3' gives
5000K
which is what we want.
Hope this helps!
> Fixed cut error in info-redshift-temp.sh

- polybar-scripts/player-mpris-tail/README.md
- polybar-scripts/player-mpris-tail/player-ctrl.sh
- polybar-scripts/player-mpris-tail/player-mpris-tail.py
Added wrapper script for playerctl that will auto-pick the same player for control as player-mpris-tail.py is displaying.
Optimised picking the right player.
Changed picking order to pick the last available, to try to always get the newest opened player.
> Control the active player

- polybar-scripts/info-hackspeed/README.md
- polybar-scripts/info-hackspeed/info-hackspeed.sh
* Remove env var mention in hackspeed README:
> Set the environment variable KEYBOARD_ID (see Configuration below) or change the default value in the script.
This is wrong. An oversight while separating my changes into two commits, my bad.
* Remove variable ICON:
This isn't needed any more. It's easier to just change the variable FORMAT now that environment variables aren't supported.
> hackspeed: some little tweaks

- polybar-scripts/inbox-reddit/inbox-reddit.sh
First of all, a big thank you for the many scripts ideas you submit. I notified an error in the `inbox-reddit.sh` script about retrieving unread messages from our Reddit account.
Indeed, it frequently happened to have this error message:
`./inbox-reddit.sh: line 6: [: : integer expression expected`
I therefore took the trouble to find a solution and also to modify certain minor elements.
> Fix inbox-reddit

- polybar-scripts/player-moc/README.md
- polybar-scripts/player-moc/player-moc.sh
When I press an 's' on the keyboard for the mocp to stop playing, the module keeps displaying information from the last song, it would not be better to add an if in the shell script to when the mocp stops it printing an empty echo, or something else, only to update the information in the module?
As it says in the wiki:
"If you want that your module disappear from the bar in some case your output has to be created with echo" "Otherwise an outdated output is still on the bar. See # 504."
And one more thing, which I think I could improve on, is that the previous module allowed a wide text to appear on the bar and disrupt the placement of the other adjacent modules, so I added the label-maxlen to correct that.
I also changed the interval because I believe that 5 seconds is too much for the …
> The player-moc will not disappear when the moc stops playing music and its text too wide.

- polybar-scripts/openweathermap-detailed/openweathermap-detailed.sh
- polybar-scripts/openweathermap-forecast/openweathermap-forecast.sh
- polybar-scripts/openweathermap-fullfeatured/openweathermap-fullfeatured.sh
- polybar-scripts/openweathermap-simple/openweathermap-simple.sh
According to the [OpenWeatherMap API documentation](https://openweathermap.org/weather-data), it is possible for it to return more than one object in the `weather` array. Example:
```json
...
"weather":[
{"id":520,"main":"rain","description":"light intensity shower rain","icon":"09d"},
{"id":500,"main":"rain","description":"light rain","icon":"10d"},
{"id":701,"main":"mist","description":"mist","icon":"50d"}
],
...
```
The jq query used to get the icon from the API response would return a list of all the icons in each of the weather objects and pass it to the `get_icon` function. The function would not identify it as a valid value and return the default one instead.
To fix this, I changed the query to only return the icon of the first object in the list.
> Fix openweathermap scripts for when the API returns more than icon

- polybar-scripts/system-uptime-pretty/system-uptime-pretty.sh
On my machine, `uptime --pretty` also outputs the week.  This PR replaces `weeks,` with `w`.
> system-uptime-pretty: replace 'weeks' with 'w'

- polybar-scripts/pulseaudio-tail/pulseaudio-tail.sh
Without the `-q` flag and with headphones connected, the command `pacmd list-sinks | grep active | head -n 1 | grep headphone` output: `ctive port: <analog-output-headphones>` is printed to Polybar every time the volume is changed.
> Fix headphone list-sink printing to Polybar

- polybar-scripts/updates-arch-aur/updates-arch-aur.sh
- polybar-scripts/updates-arch-combined/updates-arch-combined.sh
- polybar-scripts/updates-arch/updates-arch.sh
Alternative implementation of `yay` support. Won't actually be viable until `yay` fixes their error output.
See #77 for more info.
> Added comments about yay and pacman

- polybar-scripts/player-moc/player-moc.sh
Not every file necessarily has the song field set to anything. In those
cases to avoid empty output, e.i. " - ", the filename is printed instead.
> Make player-moc use filename if no song name

- polybar-scripts/player-mpris-tail/player-mpris-tail.py
Currently the script prints the status of each player as soon as it has it. This pull request changes that so a status is only printed once all players have been read and the most likely current one detected (or none have been).
This fixes the issue where the status is always stopped when running certain players in the background.
> player-mpris-tail: Only print status from current player

- .travis.yml
Just some travis optimizations I noticed could be done. Setting a generic language prevents travis from doing C specific stuff which we don't need. Not needing to download shellcheck should also speed up the process.
> Travis refactor

- polybar-scripts/pulseaudio-tail/pulseaudio-tail.sh
This PR makes it possible to track the default sink.
Right now pulseaudio-tail uses only one sink, which is defined by the $sink variable. But that has some limitations. E.g. users that have more than one sound card may want to display the sink that is active.
> pulseaudio-tail: Add default sink

- polybar-scripts/updates-fedora/updates-fedora.sh
FIXES:
* dnf upgrade needs sudo to be executed
* add space to remove the matching 'dependencies' string in $integer
> Fixes for fedora update checker

- polybar-scripts/player-mpris-tail/player-mpris-tail.py
The `{position}` tag can now be used to get the progress on the current track and display it. For now, only display as a time is supported, but I can add display as a progress bar if it people wish so.
The code tries not to make too frequent calls to dbus, and is disabled when not using it in order to save battery.
> Make player-mpris-tail able to handle position in the current track

- polybar-scripts/updates-void/README.md
- polybar-scripts/updates-void/updates-void.sh
Checking for updates doesn't require any special privileges, the script is safer like this.
> Remove unnecessary use of sudo in updates-void

- README.md
I just made my script `polify` public, and thought it somehow belonged in this collection. But since it is more of a utility then a script in the scripts directory of this repo i added it to the 'see also' section of the readme. I have some "modules"/scripts that use polify, that i can push later if you guys think it fits.
> readme: added budlabs/polify to see also

- polybar-scripts/info-wifionice/info-wifionice.sh
This ensures that the output is removed if the network is no longer
reachable.
The script is enclosed with an additional if-clause that does a iwgetid -r request, which outputs the current ESSID from that wifi network one is connected to.
> Check Wifi-ESSID for WIFIonICE

- polybar-scripts/player-mpris-tail/player-mpris-tail.py
Some players (Tauon so far) don't seem to trigger `NameOwnerChanged` when they start, so the signal handler for `PropertiesChanged` isn't attached initially.
This PR listens to all signals on `/org/mpris/MediaPlayer2` and specifically catches any that wouldn't be caught due to the missing signal handler and forwards them.
This only seems to happen on the first player change, so no further changes should be necessary.
> Get player updates without `NameOwnerChanged` #fixes 188

- polybar-scripts/player-mpris-tail/player-mpris-tail.py
This helps with #184 in that it applies the previous patch by @Rapiz1 as well as using the same logic for similar code so the names are correct when using the `list` command to find the name to blacklist.
> Use part after the 3rd '.' as name. Fixes chromium blacklist

- polybar-scripts/player-mpris-tail/player-mpris-tail.py
Looks like there's a typo in https://github.com/polybar/polybar-scripts/pull/192, which results in an exception being thrown consistently. 
I don't know what situation it happens, but it's reliable, and this fixes it.
> Correctly parse multiple artist metadata

- polybar-scripts/updates-arch-aur/updates-arch-aur.sh
- polybar-scripts/updates-arch-combined/updates-arch-combined.sh
`rua upgrade --printonly` will sometimes output a rust error (for instance when no internet connection is present)
These commits void that output while returning 0 for the number outdated repositories.
> Fix error output in rua upgrade

- polybar-scripts/player-mpris-tail/player-mpris-tail.py
When initially running player-mpris-tail.py, it displays the current
track being played without issue. However when the track is changed
(whether that's skipping to the next, or restarting current) [two
exceptions] get thrown causing the script's output to be replaced with
`ERROR:dbus.connection:Exception in handler for D-Bus signal:`.
The first—`Playback position not available`—is fixed by catching
`dbus.exceptions.DBusException` so we can set a sane default for
`speed_us` when the track's playback position isn't available.
The second—introduced with the fix for #188—is caused by listening for
all signals, some of which don't send the `properties` and `signature`
arguments which are required by the `onMPRISSignal` handler.
As we're only taking action on the `PropertiesChanged` signal, we …
> [player-mpris-tail] Fix dbus.connection exceptions

- polybar-scripts/player-mpris-tail/player-mpris-tail.py
When receiving malformed metadata, this script would react in unexpected ways. I added a couple typecasts to make sure metadata comes in as expected.
Examples of malformed metadata:
When playing video in chromium, the Artist field would be represented with a string. This would then pass into line 269, and return only the first character of the Artist field, as it would be a string typecast as a list. Checking immediately beforehand if the artist is a string keeps this from happening.
When playing video in smplayer, (and this may be specific to some of my files,) length is returned as a float. Unfortunately, it's not a literal float, it's a string representation of a float. This means, when the script tries to cast length as an int, it crashes with a ValueError, since you can't have …
> player-mpris-tail - Fixed issues with malformed metadata

- polybar-scripts/battery-combined-tlp/battery-combined-tlp.sh
"Charge total" doesn't exist in laptops with one battery, TLP simply displays the "Charge" for the single battery.
The output is purposefully reversed to find the first match backwards, whether that's "Charge total" or simply "Charge" in cases where "Charge total" doesn't exist.
> battery-combined-tlp: support laptops with one battery

- polybar-scripts/network-publicip/info-publicip.sh
$(curl -4 -sf ifconfig.co)" instead of 
$(curl -4 -sf ifconf4 ig.co)"
> Fix typo or accidental modification in the network-publicip script

- polybar-scripts/player-cmus/player-cmus.sh
When CMUS is started for the first time, cmus-remote doesn't return
any track data, which means $duration is an empty string. This causes
the script to fail with an error on line 12 when it tries to evaluate
$duration as an integer.
The fix is to only print any information if we have either a title or
an artist, which means we probably also have a duration as well.
> player-cmus: handle no file information

- README.md
It is a Shell script, and is designed to work with Polybar, but can also be used alone.
1. Support media player implement with MPRIS DBus interface (VLC/cmus/Spotify/Audacious/Clementine/Rhythmbox ...);
2. Support Web browser (Google Chrome/Chromium/Brave/Mozilla Firefox ...);
3. Support play action (Play/Pause/PlayPause/Stop);
4. Support track position seek (backward/forward), position set;
5. Support player sink volume action (mute/unmute/up/down);
6. Support current track info display via notification deamon;
7. Support player session reset;
8. Support multi players selection menu when session is empty;
9. Support current player instance process kill;
10. Support Spotify official client advertisement mute until normal track playing (just click 'next' icon (nerd font uf9ab) on Polybar …
> Add mpris_player_control link to the repo

- README.md
It's a simple widget that uses toggl.com API to get your current running task info and display it.
> Add my Toggl.com time tracker widget to the list

- polybar-scripts/system-fan-speed/system-fan-speed.sh
Fix issue with speed expression returning empty string instead of integer.
> system-fan-speed: fix empty speed

- README.md
The module [taskwarrior-polybar](https://github.com/dakuten/taskwarrior-polybar) only display a single task to polybar. The user can't view any other task unless they finish the current task and mark it done.
With this script, multiple tasks can be viewed by left clicking the module and can be marked done by right clicking. Before the action is carried out, a message is displayed for 2 second in which the user can cancel the action.
> I created an improved version of taskwarrior-polybar

- polybar-scripts/notification-xkcd/notification-xkcd.py
This pull request removes the error thrown when there isn't any internet available, and instead shows the latest comic number stored on disk.
> notification-xkcd: Added error handling for no internet

- polybar-scripts/player-mpris-tail/player-mpris-tail.py
I run player-mpris-tail.py and add chrome into blacklist. However, the module output changed while chrome player status changed. Although chrome is in the blacklist, it does not check in  ``onChangedProperties``, and chrome will be recognized as the new player.
> player-mpris-tail: fixed blacklist bug in onChangedProperties

- polybar-scripts/info-softwarecounter/info-softwarecounter.py
Workaround for when `wmctl` return a PID of `'0'`.
> Fix bug #291

- polybar-scripts/player-mpris-tail/player-mpris-tail.py
This PR will fix an issue when metadata(s) with empty array value `[]` is sent by the player.
Also, this commit will rename the function `_firstIfList` to `_metadataGetFirstItem`. The new name reflects to what the function actually do.
I'm sorry for the messy PR I did before. I forgot how to GitHub.
> player-mpris-tail: Handle empty array metadata correctly. Fixes #295

- polybar-scripts/system-bluetooth-bluetoothctl/system-bluetooth-bluetoothctl.sh
Replaces a pipe into a "`while read`"-statement with a simple for loop.
This has the advantage that a new subshell is not created because of the pipe, meaning the counter variable can be used outside of the loop. Also, i'd argue it's easier to read.
> system-bluetooth-bluetoothctl: Remove pipe

- polybar-scripts/info-hlwm-workspaces/info-hlwm-workspaces.sh
This adds support for using the info-hlwm-workspaces.sh script on a multi monitor setup.
It expects MONITOR environment variable to be set for each instance of polybar. If the MONITOR variable is not set this will still be working, however there will be no distinction between the different monitors.
This enables formatting the tags considering whether the current monitor is focused or not.
Also if one clicks on one of the tags in polybar, the script will ensure that the monitor is focused where the user clicked the tag. This prevents the effect that if one clicks a tag on an unfocused monitor, the tag will change on the other, focused monitor. This is eventually unexpected behaviour.
> Added support for multi monitor setups to herbstluftwm workspace info

- polybar-scripts/updates-pacman-aurhelper/updates-pacman-aurhelper.sh
The shebang in _updates-pacman-aurhelper_ is incorrect as it assumes that the user has sh symlinked to bash. That is the case by default in arch, but its still not a safe assumption.
Specifically, the line that is using a bash'ism is the following:
```sh
updates=$(("$updates_arch" + "$updates_aur"))
```
> Fixed shebang for updates-pacman-aurhelper

- polybar-scripts/player-mpris-tail/README.md
- polybar-scripts/player-mpris-tail/player-mpris-tail.py
Add whitelist support for module player-mpris-tail:
1. drop duplicated word '**be**' in option ``--blacklist`` help message.
2. change ``PlayerManager.__init__(blacklist = [], connect = True)`` into ``PlayerManager.__init__(filter_list, block_mode = True, connect = True)``, and remove list default parameter value, which is not a good [pattern](https://stackoverflow.com/questions/1132941/least-astonishment-and-the-mutable-default-argument).
3. keep option ``--blacklist`` and add option ``--whitelist`` for command line backward.
> player-mpris-tail: add whitelist support

- README.md
Adds [mil-ad/polybar-wireguard](https://github.com/mil-ad/polybar-wireguard) to the list of user repos.
This is a simple script that displays the current active Wireguard VPN. Mouse clicks can be mapped to connect/disconnect.
> Added a link to polybar-wireguard repo

- README.md
Hello!  This PR updates the README by grouping the other user repos by subject (tasks, spotify, etc). I added a repo of my own to the blue light filter group, and I removed the MaxdSre/mpris-player-control link since it 404s and I couldn't find what it should be. 
Thank you!
> Update README - categorize other repos, add my own, remove a 404

- polybar-scripts/pipewire-microphone/README.md
- polybar-scripts/pipewire-microphone/pipewire-microphone.sh
Add script for showing and toggling the mute state of the PipeWire default source (microphone). Based on [pulseaudio-microphone](https://github.com/polybar/polybar-scripts/tree/master/polybar-scripts/pulseaudio-microphone).
> pipewire-microphone: add pipewire-microphone

- polybar-scripts/info-wifionice/info-wifionice.sh
The current info-wifionice script checks whether the current SSID is `WIFIonICE`, then curls a URL from the train's intranet and json-parses that. This fails when the entire network traffic is routed through a VPN, since in that case, the wifi SSID matches but curling the URL returns content from outside the train's intranet.
I added a fix which checks for non-json content and shows a helpful message if necessary.
The curl response outside the train network is `<html> <head> <meta http-equiv="refresh" content="0; URL=https://www.bahn.de/service/zug/ice-portal"> </head></html>`, and trying to json-parse this without this fix will display `parse error: Invalid numeric literal at line 1, column 7` in polybar.
> info-wifionice: Add failsafe for VPN usage

- polybar-scripts/pipewire-simple/pipewire-simple.sh
There was an issue with the regex not properly matching the name of the device from pactl.  This should fix it (and is probably a better implementation).
> Simplify and fix pipewire-simple regex

- polybar-scripts/info-cava/info-cava.py
Missing newline character prevented conf_channels from being added to temp config file properly, and Cava's default stereo visualization would always be used as a fallback instead.
> Fixed mono visualizations from not being able to appear

- polybar-scripts/updates-flatpak/updates-flatpak.sh
Adjusted the output to display the correct value of updates , removing the Nothing, Proceed and empty lines to list the correct value of updates without over or under numbering
> updates-flatpak: output correction about update numbers

- polybar-scripts/network-networkmanager/network-networkmanager.sh
- polybar-scripts/system-bluetooth-bluetoothctl/system-bluetooth-bluetoothctl.sh
If `#!/bin/sh` is linked to dash or any strictly POSIX compliant shell, these scripts will give a `read: arg count` error as the standard `read` utility requires at least one variable's name. These changes fix this issue.
> Fix sh errors with POSIX read

- README.md
Merged polybar-hackernews into polybar-news in order to make the module more modular, this way there is no need to have two scripts! sorry :100:
> docs: :memo: remove polybar-hackernews

- polybar-scripts/network-networkmanager/network-networkmanager.sh
Currently the script prints a loopback interface if it exists alongside WiFi, Ethernet etc. This commit fixes this behaviour.
> Fix bug in network-networkmanager script showing loopback interface

- polybar-scripts/system-bluetooth-bluetoothctl/README.md
- polybar-scripts/system-bluetooth-bluetoothctl/system-bluetooth-bluetoothctl.sh
This commit adds the printing of the Bluetooth device battery percentage to the script.
> system-bluetooth-bluetoothctl: add bluetooth battery reporting

- polybar-scripts/pipewire-microphone/README.md
- polybar-scripts/pipewire-microphone/pipewire-microphone.sh
The `--list-targets` option was removed from `pw-cat` in [ecff225b](https://gitlab.freedesktop.org/pipewire/pipewire/-/commit/ecff225b11a29ecc9754e67de7a462f529e8e2a6), which broke the script (#436).
In my opinion it's not really necessary, since it can be done with `pactl`.
Other changes mainly concern style/efficiency.
> fix pipewire-microphone

- polybar-scripts/pulseaudio-microphone/pulseaudio-microphone.sh
When I was setting up the pulseaudio-microphone on my new laptop, it couldn't recognize my internal microphone. It was returning a random string that I can't remember. So, I decided to change the `$DEFAULT_SOURCE` variable to `@DEFAULT_SOURCE@`, which is an internal value of `pactl`
> pulseaudio-microphone: using @DEFAULT_SOURCE@ instead

- polybar-scripts/notification-spacex/notification-spacex.sh
api.spacexdata.com is no longer updated. See https://github.com/r-spacex/SpaceX-API/pull/1329
Marking this as a draft for now because I'm waiting for the next launch to make sure the changes work correctly.
> notification-spacex: migrate from spacexdata to launchlibrary

- polybar-scripts/info-hackspeed/README.md
- polybar-scripts/info-hackspeed/info-hackspeed.sh
Adds a TARGET parameter that changes the output of the script to a different format, set using TARGET_FORMAT when the wpm or cpm (depending on the value of METRIC) value exceeds that of the set TARGET. The idea being that you can set a wpm or cpm goal and see if you are achieving it.
> info-hackspeed: add format changing on the reaching of a arbitrary goal

- polybar-scripts/notification-spacex/notification-spacex.sh
This is a bugfix for my previous PR #449
When there are no upcoming launches, "jq" returns the string "null". Since the old version of the script directly recieved a timestamp, it silently cast it to a number 0 during calculations, but the new version uses the "date" command for parsing an ISO 8601 string, where this errors out instead.
> notification-spacex: Bugfix for when there are no upcoming launches

- polybar-scripts/updates-dnf/updates-dnf.sh
In the new version of dnf the --list parameter was replaced by just list as can be seen below
dnf --version
dnf5 version 5.2.12.0
With --list
dnf updateinfo -q --list | wc -l 
Unknown argument "--list" for command "updateinfo". Add "--help" for more information about the arguments.
The argument is available for commands: repoquery. (Must be placed after the command.)
Only list
dnf updateinfo -q list | wc -l 
0
> Adjusting the updateinfo parameter from --list to list only

- polybar-scripts/info-wifionice/info-wifionice.sh
Deutsche Bahn has blessed us with an extra decimal point for train travel speeds.
This breaks the current script which assumes that speeds are integers.
This PR adds support for float-typed speeds.
> info-wifionice: add support for float-typed speed
