polybar-scripts/bbswitch/README.md, polybar-scripts/bbswitch/bbswitch.sh
I made this simple module for the polybar, to show if the nvidia graphics card are actually working in notebooks. It is possible that other people already have something of the type, but I decided to add this one to the repository.
=> I make a simple module for polybar: system-nvidia-bbswitch

polybar-scripts/openweathermap-fullfeatured/openweathermap-fullfeatured.sh
openweathermap-fullfeatured.sh: arithmetic expression: expecting primary: ""1518196038"-"1518189984""
=> fix for issue : arithmetic expression: expecting primary

polybar-scripts/player-mpris-tail/player-mpris-tail.py
…as well as showing information about the current status, if a player is already running
=> Support for getting the active player

README.md
Link to other user repo: UnseenMail
=> UnseenMail

README.md
Hello. Possible to add battery indicator reference (writen by me) in this repo? :)
=> Add: polybar another battery

polybar-scripts/player-moc/README.md
[player-mocp]: Now middle click toggles pause instead of only pausing.
=> [player-moc] Toggle pause instead of pause

polybar-scripts/player-mpris-tail/README.md, polybar-scripts/player-mpris-tail/player-mpris-tail.py
The rewrite that has been tested in #35.
=> Rewrite, documentation and support for new `truncate-text` arg

polybar-scripts/player-mpris-tail/player-mpris-tail.py
=> Added support for Spotify's metadata

polybar-scripts/openweathermap-detailed/openweathermap-detailed.sh, polybar-scripts/openweathermap-forecast/openweathermap-forecast.sh, polybar-scripts/openweathermap-fullfeatured/openweathermap-fullfeatured.sh, polybar-scripts/openweathermap-simple/openweathermap-simple.sh
Also factor out the API into a variable. Reads better and it will make
it easier to make future changes (if any).
=> openweathermap-*: Use HTTPS instead of HTTP for the API endpoint.

polybar-scripts/news-archlinux/news-archlinux.py
=> removed unnecessary lines

polybar-scripts/updates-void/README.md, polybar-scripts/updates-void/updates-void.sh
This is my first pull request, let me know if I screwed up
=> Add view updates script for Void Linux

polybar-scripts/popup-calendar/README.md, polybar-scripts/popup-calendar/popup-calendar.sh
=> yad popup calendar - add auto bottom detect & out of screen position fix

polybar-scripts/info-hackspeed/info-hackspeed.sh
I've added an aditional keyboard layout to the info-hackspeed module.
=> added qwertz keyboard layout to info-hackspeed module

polybar-scripts/popup-calendar/README.md, polybar-scripts/popup-calendar/popup-calendar.sh
- calendar now sticky
- prevent open new calendar when previous one still open
- added border size parameter to better position calculating
- fixed previously wrong default calendar size parameters
- fixed magic numbers in formulas
- added comment about yad min size
=> Fix popup-calendar

README.md
Python script to compare latest available Node.js version to the installed
=> Added polybar node-version

polybar-scripts/network-traffic/network-traffic.sh, polybar-scripts/player-cmus/player-cmus.sh
Add cmus player state "stopped" for internet streams
More clean view for internet streams without duration
Fix error messages with arithmetic operations
=> Add features and fix

polybar-scripts/popup-calendar/popup-calendar.sh
Alignment fixed https://github.com/polybar/polybar-scripts/issues/171
=> popup-calendar: Fix yad border calculation & remove magic numbers

polybar-scripts/openweathermap-detailed/README.md, polybar-scripts/openweathermap-simple/README.md
Some small fixes that improve the README consistency.
=> Openweather readme fixes

polybar-scripts/updates-arch-aur/updates-arch-aur.sh, polybar-scripts/updates-arch-combined/updates-arch-combined.sh
Adding support for rua as [it now supports only listing packages](https://github.com/vn971/rua/issues/86).
=> Add rua support to updates-arch-[aur|combined]

polybar-scripts/player-mpris-tail/player-mpris-tail.py
This PR refactors `Player._parseMetadata` to increase the readability and also adds some flexibility to the function in some cases that might occur in the future like strange or non-conformant metadata format.
In my case, I've found that cmus sends `xesam:title` and `xesam:album` as an array of string (even though it only contains one string) instead of a string as per MPRIS metadata specification, causing this error to occur:
```
Traceback (most recent call last):
File "/home/rocky-i3/Scripts/polybar-player-mpris-tail", line 509, in <module>
PlayerManager(blacklist = args.blacklist)
File "/home/rocky-i3/Scripts/polybar-player-mpris-tail", line 32, in __init__
self.refreshPlayerList()
File "/home/rocky-i3/Scripts/polybar-player-mpris-tail", line 84, in refreshPlayerList …
```
=> player-mpris-tail: Refactor and fix metadata parsing function

polybar-scripts/player-mpris-tail/player-mpris-tail.py
=> Fix for parsing year when no date is set

polybar-scripts/info-hackspeed/info-hackspeed.sh
It just counts the letters a-z and the numbers 0-9.
=> Add Dvorak layout to info-hackspeed.

README.md
Hi, I made a script to display online channels on twitch, it takes a username or a list of channels. If the output is too long it will scroll.
=> Add polybar-twitch

README.md
Hey guys,
I just released a couple of lightweight programs with minimal dependencies written in C that help integrate spotify info and controls into polybar. I'd love for you guys to link to my repo in the README.
https://github.com/mihirlad55/polybar-spotify-module
Thanks,
Mihir
=> README.md: Add polybar-spotify-module link to repo

polybar-scripts/pulseaudio-microphone/README.md, polybar-scripts/pulseaudio-microphone/pulseaudio-microphone.sh
Hi, I made a script that shows if the default microphone is muted or not. Useful for calls.
=> Add pulseaudio-microphone

README.md
I have just added a link to a simple and customizable timer script.
=> added link to polybar-timer repository

README.md
I have just built an indicator for the amount of todoist tasks of each priority.
I would be delighted to see the link in the README. Thank you. :)
=> added jbirnick/polybar-todoist to README

README.md
Hey everyone,
First of all thanks for hosting this beautiful collection of polybar modules. Coming to my module, it is different than the other ones as it features text scrolling. Also, since it is directly using [playerctl](https://github.com/altdesktop/playerctl/), the scripts are very minimal and easy to customize. I've run the `shellcheck` tests and the scripts do pass that.
Here's the repo: https://github.com/PrayagS/polybar-spotify
Thanks,
Prayag Savsani.
=> README.md: Add polybar-spotify link to the repo

README.md
Hey all. I'm tacking on a VPN module I made to the README, until I feel it's ready to be de-glyphed and added to the polybar-scripts subdirectory. (Ready in this case means easily able to incorporate other popular VPN's.)
Thanks!
=> added polybar-vpn-controller to list of user repos

polybar-scripts/notification-xkcd/README.md, polybar-scripts/notification-xkcd/notification-xkcd.py
This pull request adds handling for if the save file doesn't exist (now it creates a new one, previously it crashed), and removes unnecessary writes to the save file.
=> notification-xkcd: minor fixes

README.md
=> Add polybar-i3-window to user repos

polybar-scripts/system-gpu-optimus/system-gpu-optimus.sh
Had to touch this up for it to work on my Arch system with Optimus Manager Version 1.3
=> Optimus Touch Up

polybar-scripts/pulseaudio-microphone/README.md, polybar-scripts/pulseaudio-microphone/pulseaudio-microphone.sh
The module also shows the current volume percent (when not muted)
Cheers!
=> Allow change of mic volume using the scroll wheel

polybar-scripts/info-softwarecounter/info-softwarecounter.py
I have some improvments for this script I like very much. 
I hope you appreciate them. :wink:
BR and happy new year :blush:
=> info-softwarecounter: the whole script has been refactored

polybar-scripts/system-ati-radeontop/README.md, polybar-scripts/system-ati-radeontop/system-ati-radeontop.sh
After messing around with this a bit I found that I can make use of polybar's ability to listen for continuous output, which radeontop and grep are both capable of providing.
This newer configuration results in the same output without constantly starting new processes.
=> Improved system-ati-radeontop

README.md
=> add xi/polybar-status-indicators to README

README.md
I wrote that module, so I thought I'd add a reference to it here.
=> Add user repo for tailscale VPN module to README

polybar-scripts/pipewire-simple/README.md, polybar-scripts/pipewire-simple/pipewire-simple.sh
=> switch from pw-play to pactl

README.md
=> Add a script to monitor NetworkManager connection to user repos

polybar-scripts/info-timew/README.md, polybar-scripts/info-timew/info-timew.sh, polybar-scripts/info-timew/timew.sh
This script displays the daily tracked time. You can click it, to start tracking, using timew.
=> feat(info-timew): add info-timew script

polybar-scripts/openweathermap-detailed/openweathermap-detailed.sh, polybar-scripts/openweathermap-forecast/openweathermap-forecast.sh, polybar-scripts/openweathermap-fullfeatured/openweathermap-fullfeatured.sh, polybar-scripts/openweathermap-simple/openweathermap-simple.sh
Added missing quotes to curl commands like requested in #395 .
=> Added missing quotes to curl commands (see #395)

polybar-scripts/notification-spacex/notification-spacex.sh
The v3 API no longer recieves new data since November 2020
=> notification-spacex: Upgrade to v5 API

polybar-scripts/info-timew/README.md, polybar-scripts/info-timew/info-timew.sh
introduce weekday toggle to info-timew to view either weekly or daily time spend
=> introduce weekday toggle to info-timew

README.md
Added a new polybar module that displays tasks from Notion with their API
=> feat: :memo: Add notion todo module to README.md

README.md
Show/toggle Liked/Saved status of currently playing Spotify song along (with basic controls)
=> Added mikeboiko/spotidry

README.md
`uair` is a simple, yet extensible timer for status bars, command-line and graphical user interfaces with support for multiple synchronized timers.
=> Add uair to tasks/timers category

README.md
Hi, would you like to add a link to my module under the WM/System section?
https://github.com/tuurep/windowlist
For those familiar with [polywins](https://github.com/uniquepointer/polywins), this is a direct continuation on that.  
(above link is a mirror because original polywins repo no longer exists)
=> README.md: add tuurep/windowlist to user repos

README.md
turn your polybar clock into a binary clock!
=> add a collection of fonts to README

README.md
Programming Wisdom is a simple snippet for various tiling wm bar plugins (including polybar) which displays excerpts, proverbs, quotes and other wisdoms from across programming spectrum, based on 600+ assorted texts. 
Installation/configuration instructions are in repository README.
=> Update readme, add exaroth/programming-wisdom link
